#%RAML 1.0 Overlay
extends: api.raml

uses: 
  luvio: luvio://annotations.raml

(luvio.keyPrefix): 'dadapp::'

types:
  Joke: 
    (luvio.key):
      id: _id

/jokes: 
  get: 
    (luvio.adapter):
      name: getJokes

/jokes/{id}:
  get: 
    (luvio.adapter):
      name: getJoke
